stages:
  - build
  - push

variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE

before_script:
  - 'if [ "$CI_COMMIT_BRANCH" = "master" ]; then export IMAGE_TAG=latest; else export IMAGE_TAG=$(echo $CI_COMMIT_REF_NAME | sed -e "s/[^a-zA-Z0-9_.-]/-/g"); fi'
  - echo "Image tag set to $IMAGE_TAG"

build_and_push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --build-arg BUILD_VERSION=$CI_COMMIT_SHORT_SHA -t $DOCKER_IMAGE_NAME:$IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
